# Generated by Django 2.1.2 on 2019-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(blank=True, db_column='ORG_ID', null=True)),
                ('client_id', models.IntegerField(blank=True, db_column='CLIENT_ID', null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=200, null=True)),
                ('isactive', models.CharField(blank=True, db_column='ISACTIVE', max_length=10, null=True)),
                ('created', models.DateTimeField(blank=True, db_column='CREATED', null=True)),
                ('createby', models.IntegerField(blank=True, db_column='CREATEBY', null=True)),
                ('updated', models.DateTimeField(blank=True, db_column='UPDATED', null=True)),
                ('updateby', models.IntegerField(blank=True, db_column='UPDATEBY', null=True)),
                ('remove', models.CharField(blank=True, db_column='REMOVE', max_length=1, null=True)),
                ('imgset_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'employee_info',
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('oldperson_id', models.IntegerField(blank=True, null=True)),
                ('pic_name', models.CharField(blank=True, max_length=45, null=True)),
                ('isUpdate', models.IntegerField()),
            ],
            options={
                'db_table': 'event_info',
            },
        ),
        migrations.CreateModel(
            name='OldpersonInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(blank=True, db_column='ORG_ID', null=True)),
                ('client_id', models.IntegerField(blank=True, db_column='CLIENT_ID', null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('imgset_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=200, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('firstguardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('firstguardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('firstguardian_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('firstguardian_wechat', models.CharField(blank=True, max_length=50, null=True)),
                ('secondguardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('secondguardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('secondguardian_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('isactive', models.CharField(blank=True, db_column='ISACTIVE', max_length=10, null=True)),
                ('created', models.DateTimeField(blank=True, db_column='CREATED', null=True)),
                ('createby', models.IntegerField(blank=True, db_column='CREATEBY', null=True)),
                ('updated', models.DateTimeField(blank=True, db_column='UPDATED', null=True)),
                ('updateby', models.IntegerField(blank=True, db_column='UPDATEBY', null=True)),
                ('remove', models.CharField(blank=True, db_column='REMOVE', max_length=1, null=True)),
            ],
            options={
                'db_table': 'oldperson_info',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(db_column='ORG_ID')),
                ('client_id', models.IntegerField(db_column='CLIENT_ID')),
                ('username', models.CharField(db_column='UserName', max_length=50)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('real_name', models.CharField(blank=True, db_column='REAL_NAME', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, db_column='MOBILE', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=200, null=True)),
                ('isactive', models.CharField(blank=True, db_column='ISACTIVE', max_length=10, null=True)),
                ('created', models.DateTimeField(blank=True, db_column='CREATED', null=True)),
                ('createby', models.IntegerField(blank=True, db_column='CREATEBY', null=True)),
                ('updated', models.DateTimeField(blank=True, db_column='UPDATED', null=True)),
                ('updateby', models.IntegerField(blank=True, db_column='UPDATEBY', null=True)),
                ('remove', models.CharField(blank=True, db_column='REMOVE', max_length=1, null=True)),
                ('datafilter', models.CharField(blank=True, db_column='DATAFILTER', max_length=200, null=True)),
                ('theme', models.CharField(blank=True, max_length=45, null=True)),
                ('defaultpage', models.CharField(blank=True, max_length=45, null=True)),
                ('logoimage', models.CharField(blank=True, max_length=45, null=True)),
                ('qqopenid', models.CharField(blank=True, max_length=100, null=True)),
                ('appversion', models.CharField(blank=True, max_length=10, null=True)),
                ('jsonauth', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='VolunteerInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(blank=True, db_column='ORG_ID', null=True)),
                ('client_id', models.IntegerField(blank=True, db_column='CLIENT_ID', null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.CharField(blank=True, db_column='ISACTIVE', max_length=10, null=True)),
                ('created', models.DateTimeField(blank=True, db_column='CREATED', null=True)),
                ('createby', models.IntegerField(blank=True, db_column='CREATEBY', null=True)),
                ('updated', models.DateTimeField(blank=True, db_column='UPDATED', null=True)),
                ('updateby', models.IntegerField(blank=True, db_column='UPDATEBY', null=True)),
                ('remove', models.CharField(blank=True, db_column='REMOVE', max_length=1, null=True)),
                ('imgset_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'volunteer_info',
            },
        ),
    ]
